### PR TITLE
ERROR - regs.isError: 

### PR DESCRIPTION
**Pull request by ghuening**
Hi,
I try to connect a Kaco 6TL3 to Venus on a Pi 3. The connection starts ok, data are correct but after a time it fails.

my log is below.

THX for help!

BR
Guenter

@4000000063d006f600502594 2023-01-24 16:27:24,004 - DbusKaco - ERROR - regs.isError: {regs}
@4000000063d006f92ebc978c 2023-01-24 16:27:27,783 - DbusKaco - INFO - Startup, trying connection to Modbus-Server: ModbusTCP 192.168.1.100:502, UNIT 1
@4000000063d006fc2f210294 2023-01-24 16:27:30,789 - pymodbus.client.sync - ERROR - Connection to (192.168.1.100, 502) failed: timed out
@4000000063d006fc2f2fd38c 2023-01-24 16:27:30,790 - DbusKaco - ERROR - unable to connect to 192.168.1.100:502
@4000000063d0070009710bac 2023-01-24 16:27:34,157 - DbusKaco - INFO - Startup, trying connection to Modbus-Server: ModbusTCP 192.168.1.100:502, UNIT 1
@4000000063d0070309cabc9c 2023-01-24 16:27:37,163 - pymodbus.client.sync - ERROR - Connection to (192.168.1.100, 502) failed: timed out
@4000000063d0070309d46d14 2023-01-24 16:27:37,164 - DbusKaco - ERROR - unable to connect to 192.168.1.100:502
@4000000063d007060eca1c24 2023-01-24 16:27:40,247 - DbusKaco - INFO - Startup, trying connection to Modbus-Server: ModbusTCP 192.168.1.100:502, UNIT 1
@4000000063d007090f4b88f4 2023-01-24 16:27:43,253 - pymodbus.client.sync - ERROR - Connection to (192.168.1.100, 502) failed: timed out
@4000000063d007090f4bb004 2023-01-24 16:27:43,254 - DbusKaco - ERROR - unable to connect to 192.168.1.100:502
@4000000063d0070c1436fed4 2023-01-24 16:27:46,338 - DbusKaco - INFO - Startup, trying connection to Modbus-Server: ModbusTCP 192.168.1.100:502, UNIT 1
@4000000063d0070c17580554 2023-01-24 16:27:46,390 - DbusKaco - INFO - Connected to Modbus Server.
@

### CODE REVIEW

**Comment by h4ckst0ck** [comment]
I can neither say why the kaco inverter terminates the connection, nor can I accept this MR.

**Comment by h4ckst0ck** [comment]
DbusKaco - ERROR - regs.isError: {regs}
Try debug/print out the  that line and check what error exactly "regs" ( +str(regs) ) is. You need to fix the register numbers for your inverter based on the documentation of it.

**Comment by ghuening** [comment]
ok, I will try thx

**Comment by ghuening** [comment]
Modbus adresses where ak, alft updateting Kaco from 3.2 to 5.5.7 it seem to be working.

Sorry for disturbing you.

Well done, thx 
BR
Guenter

**Pull request closed without merging**
